### ISSUE TITLE
同学你好，我有关于一个小小的问题想请教～～～

### ISSUE THREAD

**Issue by zssjh** [weichnn/Evaluation_Tools#1]
你好，我是东北大学研二的学生，在做SLAM方向，看到您的论文RGB-D SLAM in Dynamic Environments Using Points Correlations，写的非常好，有一个很小的问题想请教下您，不好意思，没有找到您的其他联系方式，所以只能在这问您了，这是我的qq:617068202，希望您有时间的话不吝赐教哈～

**Comment by weichnn** [comment]
Sorry to see your message too late. my email: weichendai \in hotmail.com. if you still have any questions, feel free to ask me.
